package com.c8y.ms.templates.ai.controller;


import org.springframework.ai.chat.client.ChatClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Example Controller demonstrating basic LLM prompting techniques.
 */

@RestController
@RequestMapping("/api/ai-agent/prompt")
public class PromptController {

    private final ChatClient chatClient;

    public PromptController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Example of using a fixed template with dynamic placeholder values.
     * @param deviceType The type of device (e.g., 'thermometer', 'vibration sensor').
     * @param unit The unit of measurement (e.g., 'Celsius', 'G-force').
     * @return A configuration example generated by the LLM.
     */
    @GetMapping("/templated")
    public String templatedPrompt(
            @RequestParam(value = "deviceType", defaultValue = "fan") String deviceType,
            @RequestParam(value = "unit", defaultValue = "RPM") String unit) {

        final String system = "You are an expert Cumulocity Agent who generates short 5 line SmartREST templates.";

        return chatClient.prompt()
                .system(system)
                .user(u -> {
                    u.text("Generate a SmartREST template for a {deviceType} that reports a single value in {unit}.");
                    u.param("deviceType", deviceType);
                    u.param("unit", unit);
                })
                .call()
                .content();
    }

    /**
     * Example of "Prompt Stuffing," where additional, specific context (data) given
     * is injected into the prompt. The LLM is instructed to answer based
     * on this provided context, improving accuracy and grounding the response.
     * In a real application, this data would be dynamically retrieved
     * from a Vector Database (RAG) or C8Y SDK calls.
     *
     * @param deviceId The ID of the device (used in the context).
     * @return A summary of the device's state based on the provided context.
     */
    @GetMapping("/context-stuffing")
    public String contextStuffing(@RequestParam(value = "deviceId", defaultValue = "80085") String deviceId) {

        final String deviceContext =
                """
                Device ID: """ + deviceId + """
                Status: WARNING.
                Readings: Temperature is 95C (Threshold is 90C).
                Last Maintenance: 2025-10-01 by Technician Jane.
                Location: Server Rack B, Floor 3.
                Historical Data: Device temperature frequently spikes between 93C and 96C during peak hours.
                """;

        final String system =
                """
                You are a Cumulocity IoT Maintenance Analyst. 
                Analyze the 'DEVICE CONTEXT' provided below. 
                You MUST answer the user's question ONLY using the facts present in the 'DEVICE CONTEXT'. 
                If the answer is not in the context, you must state that the information is not available.
                """;

        final String userQuery =
                "What is the current status of the device, who performed the last maintenance, " +
                        "and what historical data is relevant to the high temperature reading?";

        return chatClient.prompt()
                .system(system)
                .user(u -> {
                    u.text("DEVICE CONTEXT:\n{context}\n\nQUESTION: {query}");
                    u.param("context", deviceContext);
                    u.param("query", userQuery);
                })
                .call()
                .content();
    }
}