package com.c8y.ms.templates.ai.controller;

import com.c8y.ms.templates.ai.model.DeviceSummary;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.web.bind.annotation.*;

/**
 * A simple example REST controller that exposes an AI-powered chat endpoint using Spring AI.
 * This controller leverages Spring AI's {@link ChatClient} to send user prompts
 * to a Large Language Model (LLM) and return generated responses.
 */
@RestController
@RequestMapping("/api/ai-agent")
public class SimpleChatController {

    private final ChatClient chatClient;

    public SimpleChatController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Generates a response from the AI model based on the provided prompt (simple example).
     *
     * @param prompt the user-provided input for the AI model
     * @return the textual response produced by the AI model
     */
    @GetMapping("/chat")
    public String generateResponse(@RequestParam(value = "prompt",
            defaultValue = "What is Cumulocity IoT?") String prompt) {

        return chatClient.prompt()
                .user(prompt)
                .call()
                .content();
    }

    /**
     * Generates an unstructured response example ( here natural-language status report for a device).
     * This method constructs a fixed prompt that includes the provided device ID
     * and simulated device telemetry such as battery level and last-seen timestamp.
     *
     * @param deviceId the ID of the device to describe
     * @return a natural-language status report generated by the AI model
     *
     */
    @GetMapping("/chat/device/unstructured")
    public String deviceUnstructured(@RequestParam(value = "deviceId", defaultValue = "10200") String deviceId) {
        String prompt = String.format(
                "Based on the following data, provide a 50-word status report for Device ID: %s. " +
                        "Data: The battery is at 15%% and it last reported a measurement 3 hours ago.",
                deviceId
        );
        return chatClient.prompt()
                .user(prompt)
                .call()
                .content();
    }

    /**
     * Generates a structured response example : device summary using the AI model and maps the output
     * into a {@link DeviceSummary} record.
     *
     * @param deviceId the ID of the device whose information should be summarized
     * @return a {@link DeviceSummary} populated with AI-generated structured fields
     *
     */
    @GetMapping("/chat/device/structured")
    public DeviceSummary deviceStructured(@RequestParam(value = "deviceId", defaultValue = "10200") String deviceId) {

        String c8yDeviceData = "Device is a sensor array. Current battery is 15%. Last seen 3 hours ago. Critical alarm is active: 'High Vibration'.";

        return chatClient.prompt()
                .system("You are an expert Cumulocity IoT Agent designed to summarize device data.")
                .user(u -> {
                    u.text("Analyze the following device data for Device ID {id} and populate the requested fields in the output structure:");
                    u.param("id", deviceId);
                    u.text(c8yDeviceData); // Pass the C8Y data into the prompt
                })
                .call()
                .entity(DeviceSummary.class);
    }

    /**
     * Retrieves a full chat response example.
     * This endpoint generates a one-sentence status summary for the specified device ID.
     *
     * @param deviceId the unique identifier of the device to summarize; defaults to {@code "10200"} if not provided
     * @return the full {@link ChatResponse} object containing the generated summary and metadata
     */
    @GetMapping("/chat/device/full-response")
    public ChatResponse deviceFullResponse(@RequestParam(value = "deviceId", defaultValue = "10200") String deviceId) {
        String prompt = String.format(
                "Provide a one-sentence summary of the status for Device ID: %s. " +
                        "Status: Battery is 85%%, last seen 5 minutes ago.",
                deviceId
        );
        return chatClient.prompt()
                .user(prompt)
                .call()
                .chatResponse(); // Returns the full ChatResponse object, including metadata (tokens, model name, etc.)
    }

}